catalog: workspace
schema: default
download:
  output_dir: "/Volumes/shm/3w/bronze/"
  base_url: "https://api.github.com/repos/petrobras/3W/contents"
  max_files: null # Maximum number of files to download (null = all files)
  max_dirs: null # Maximum number of directories to scan (null = all)
  skip_existing: true # Skip files that already exist
  delay_seconds: 0.1 # Delay between downloads to be respectful to GitHub
process:
  silver_dir: "/Volumes/shm/3w/silv/"
  table: well_data
train:
  tags:
    1:
      tag: "P-PDG"
      name: "Pressure at the PDG"
      unit: "Pa"
    2:
      tag: "P-TPT"
      name: "Pressure at the TPT"
      unit: "Pa"
    3:
      tag: "T-TPT"
      name: "Temperature at the TPT"
      unit: "degC"
    4:
      tag: "P-MON-CKP"
      name: "Pressure upstream of the PCK"
      unit: "Pa"
    5:
      tag: "T-JUS-CKP"
      name: "Temperature downstream of the PCK"
      unit: "degC"
    6:
      tag: "P-JUS-CKGL"
      name: "Pressure downstream of the GLCK"
      unit: "Pa"
    7:
      tag: "QGL"
      name: "Gas lift flow rate"
      unit: "sm^3/s"
  test_ratio: 0.2
  base_model_name: "hydrate_xgboost"
deploy:
  base_hydrate_deploy_name: "hydrate_predict"
agentify:
  agent_name: well_agent
  fm_endpoint: databricks-meta-llama-3-3-70b-instruct
  tool_names:
    - predict_state
    - latest_n_obs
  system_prompt: |
    You are a helpful, expert assistant for the 3W Well Agent, designed to answer questions and provide insights about well data from the Petrobras 3W dataset. You have access to time series data from multiple wells, with each measurement described by a tag, name, and unit. You can also interpret model predictions about well states.

      ## Tag Reference
      The following tags are available in the dataset:
        - 1: "P-PDG" — Pressure at the PDG (Pa)
        - 2: "P-TPT" — Pressure at the TPT (Pa)
        - 3: "T-TPT" — Temperature at the TPT (degC)
        - 4: "P-MON-CKP" — Pressure upstream of the PCK (Pa)
        - 5: "T-JUS-CKP" — Temperature downstream of the PCK (degC)
        - 6: "P-JUS-CKGL" — Pressure downstream of the GLCK (Pa)
        - 7: "QGL" — Gas lift flow rate (sm^3/s)

      ## Model Predicted Classes
      When the model predicts a class, it refers to the following well states:
        - 0: Normal
        - 1: Abrupt Increase of BSW (Basic Sediment and Water)
        - 2: Spurious Closure of DHSV (Downhole Safety Valve)
        - 3: Severe Slugging
        - 4: Flow Instability
        - 5: Rapid Productivity Loss
        - 6: Quick Restriction in PCK (Production Choke)
        - 7: Scaling in PCK
        - 8: Hydrate in Production Line

      When you answer, always clarify the meaning of tags and predicted classes as needed. If a user asks about a tag, provide its name and unit. If a user asks about a predicted class, provide its full description. Be concise and accurate.
evaluate:
  questions:
    - "What are the latest 5 predictions?"
    - "What is the current state of Well 19?"
    - "What is the current state of Well 1023?"
    - "What wells are currently operating?"
    - "Tell me everything you know about Well 2?"